version: '3.8'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  parser_mexc:
    build: .
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    command: python mexc.py
  
  parser_swap:
    build: .
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    command: python swap.py
  
  telegram_bot:
    build: .
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    command: python bot.py

  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db