version: '3.8'

services:

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  parser_mexc:
    build: .
    # volumes:
    #   - .:/app
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    command: python mexc.py
  
  parser_swap:
    build: .
    # volumes:
    #   - .:/app
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      parser_mexc:
        condition: service_started
    command: python swap.py
  
  telegram_bot:
    build: .
    # volumes:
    #   - .:/app
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    command: python bot.py
  
  scanner:
    build: .
    # volumes:
    #   - .:/app
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    command: python scanner.py
    
  worker:
    build: .
    # volumes:
    #   - .:/app
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A worker.celery worker -B -l info
 
  mongodb:
    image: mongo:4.4 
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - data:/app

volumes:
  data: 